const server = (endpoint, params) => {
    if (endpoint === 'api/home') {
        return JSON.stringify(
            [
                {
                    title: 'Recentes',
                    innerData: [
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] },
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] },
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] }
                    ],
                    gridView: 'horizontal'
                },
                {
                    title: 'Campeões de Bilheteria',
                    innerData: [
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] },
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] },
                        { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] }
                    ],
                    gridView: 'vertical'
                },
            ]
        );
    }

    if (endpoint === 'api/movies') {
        const moviesData = [
            { id: 1, title: "Mulan", imdbGrade: 5.6, runtime: "01:30", genre: "Ação, Aventura", launchYear: "2020", sinopse: "A aclamada cineasta Niki Caro dá vida à épica lenda da icônica guerreira chinesa em Mulan, da Disney, em que uma jovem destemida arrisca a própria vida por amor à família e à pátria para se tornar uma das maiores guerreiras de toda a China. Quando o Imperador da China emite um decreto estabelecendo que um homem de cada família deve servir no exército imperial para defender o país dos invasores do Norte, Hua Mulan, a filha mais velha de um honrado guerreiro se apresenta no lugar de seu pai adoentado. Disfarçada de homem, como Hua Jun, ela é testada a cada etapa do caminho e deve controlar sua força interior e abraçar seu verdadeiro potencial. É uma jornada épica que vai transformá-la em uma reverenciada guerreira e levá-la a conquistar o respeito de uma nação agradecida... e um pai orgulhoso.", cover: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSDiNL4mplz50DO7jRQSjQZVuzqlvG-Kq5pfxK6DNKQQPbL2N2w", images: [{ url: "https://start-tv.net/wp-content/uploads/2020/09/2d786a0a-bfbf-4ad6-aa6d-d4286e3f8709-rev-1-JM-FP-0060_High_Res_JPEG-2-1024x533.jpeg" }, { url: "https://livrosfilmes2017.files.wordpress.com/2020/09/mulan-live-action-1.jpeg" }, { url: "https://codigonerd42.com/wp-content/uploads/2020/09/mulan-disney.jpg" }] },
        ];

        if(params != null && params?.q != null && params?.q != ''){
            return JSON.stringify({
                movies : moviesData.filter(movie => movie.title.toLowerCase().includes(params.q.toLowerCase()))
            });
        }else{
            return JSON.stringify({
                movies : moviesData
            });
        }
    }
}

export default api = {
    get: (endpoint, params = null) => {
        return new Promise(resolve =>
            setTimeout(() => resolve(JSON.parse(server(endpoint, params))), 2000)
          );
    }
}